---
- hosts: osmc
  become: yes
  gather_facts: no
  roles:
    - { role: common, tags: ["common"] }
    - { role: locale, tags: ["locale"] }
    - { role: nodejs, tags: ["nodejs"] }
    - { role: samba, tags: ["samba"] }
    - { role: influx, tags: ["influx"] }
    - { role: telegraf, tags: ["telegraf"] }
    - { role: grafana, tags: ["grafana"] }
    - { role: crontab, tags: ["crontab"] }
