---
- hosts: osmc
  become: yes
  tasks:
  - name: make sure en_US.UTF-8 locale are properly generated
    locale_gen:
      name: en_US.UTF-8
      state: present
  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      state: present
  - name: Install the gpg key for nodejs LTS
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_8.x stretch main"
      state: present
      update_cache: yes
  - name: Install the nodejs
    apt:
      name: nodejs
      state: latest
  - name: Install basic utils
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - mc
      - htop
      - cron

  - name: Check if Media disk is mounted
    stat:
      path: /media/Backups
    register: media

  - name: Install Samba
    apt:
      name: smb-app-osmc
      state: latest

  - name: Configure Samba
    copy:
      src: smb-shares.conf
      dest: /etc/samba/smb-shares.conf
      owner: osmc
      group: osmc
      mode: 0644
    when: media.stat.exists

  - name: Restart Samba
    service:
      name: samba
      state: restarted
    when: media.stat.exists
