- name: Copy backup scripts
  become: false
  copy:
    src: "{{ item.path }}"
    dest: "~/{{ item.path }}"
    owner: osmc
    group: osmc
    mode: 0744
  with_filetree: .
  when: item.state == 'file' and item.path == item.path|regex_search('backup_.*\.sh$')
- name: Influx backup
  become: false
  cron:
    name: "Backup InfluxDB"
    minute: 0
    hour: 0
    dow: 0
    job: "~/backup_influx.sh >> ~/backup_influx.log 2>&1"
- name: Clean old Influx backups
  become: false
  cron:
    name: "Clean old Influx backups"
    minute: 1
    hour: 0
    dow: 0
    job: "find /media/Backups/Influx/* -maxdepth 1 -type d -regex '.*-[0-9]+-[0-9]+' -mtime +37 -delete"

- name: Configure daily backups
  become: false
  cron:
    name: "Backup {{ item|capitalize }} settings"
    minute: 2
    hour: 0
    job: "~/backup_{{ item }}.sh >> ~/backup_{{ item }}.log 2>&1"
  with_items:
    - grafana
    - kodi
- name: Configure cleaning daily backups
  become: false
  cron:
    name: "Clean {{ item.name }} backups"
    minute: 3
    hour: 0
    job: "find {{ item.path }}/* -mtime +10 -delete"
  with_items:
    - { name: Grafana, path: "/media/Backups/Grafana" }
    - { name: Kodi, path: "/media/Backups/osmc\\ backup" }
