- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install basic utils
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mc
    - htop
    - cron

