- name: Add Influx GPG Key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
- name: Add Influx repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian stretch stable"
    state: present
    update_cache: yes
- name: Install Influx
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - influxdb
    - telegraf
- name: Restore database
  include_tasks: "restore.yml"
  when: restore is defined
- name: Start Influx
  service:
    name: influxdb
    state: started
