- name: Add Influx GPG Key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
- name: Add Influx repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian stretch stable"
    state: present
    update_cache: yes
- name: Install Influx
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - influxdb
    - telegraf
  notify: Restart Influx
- name: Update configuration
  ini_file:
    path: /etc/influxdb/influxdb.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "monitor", option: "store-interval", value: '"30s"' }
    - { section: "http", option: "log-enabled", value: "false" }
    - { section: "continuous_queries", option: "enabled", value: "false" }
  notify: Restart Influx
- name: Restore database
  include_tasks: "restore.yml"
  when: restore is defined
