- name: Copy TP-Link script
  copy:
    src: tplink
    dest: /home/osmc
    owner: osmc
    group: osmc
    mode: 0644

- name: Install npms
  npm:
    path: /home/osmc/tplink

- name: Change Telegraf interval
  lineinfile:
    path: /etc/telegraf/telegraf.conf
    regexp: '^\s*interval\s*=\s*"\d+s"'
    line: '  interval = "30s"'
  notify: Restart Telegraf
- name: Update Telegraf config
  blockinfile:
    path: /etc/telegraf/telegraf.conf
    block: "{{ lookup('file', 'telegraf-custom.conf') }}"
    marker: "# {mark} ANSIBLE BLOCK - static"
  notify: Restart Telegraf
- name: Enable TP-Link energy meters in Telegraf
  blockinfile:
    path: /etc/telegraf/telegraf.conf
    block: |
      [[inputs.exec]]
        commands = [
         "node /home/osmc/tplink/index.js {{ item.ip }}"
        ]
        timeout = "5s"
        name_suffix = "_tplink_{{ item.name }}"
        data_format = "json"
    marker: "# {mark} ANSIBLE BLOCK - {{ item.name }}"
  with_items:
    - { name: pc, ip: 192.168.1.135 }
    - { name: tv, ip: 192.168.1.104 }
    - { name: philips, ip: 192.168.1.82 }
  notify: Restart Telegraf
